name: macro_monitor
description: "宏观经济监控技能 — 东方财富数据中心，获取GDP/CPI/PMI/社融/M2/LPR等宏观指标和国债收益率，零API Key"
requires:
  bins: []
  env: []
permissions: []
always: false
triggers:
  - "宏观经济"
  - "经济数据"
  - "GDP"
  - "CPI"
  - "利率"
  - "国债收益率"
  - "央行"
  - "货币政策"
  - "macro economy"
  - "economic data"
  - "interest rate"
  - "bond yield"
  - "treasury"
  - "inflation"
capabilities:
  - "finance_api"
output_format: "markdown"
fallback:
  strategy: "degrade"
  message: "无法获取宏观经济数据。"
