name: stock_analysis
description: "股票分析技能 — 通过东方财富免费API获取 A股/港股/美股实时行情、K线、资金流向、财报、研报，无需任何API Key"
requires:
  bins: []
  env: []
permissions: []
always: false
triggers:
  - "股票分析"
  - "分析股票"
  - "看看股票"
  - "股价"
  - "行情"
  - "K线"
  - "基本面"
  - "研报"
  - "stock analysis"
  - "stock quote"
  - "stock price"
  - "analyze stock"
  - "查询股票"
  - "股票走势"
  - "个股分析"
  - "技术分析"
  - "涨停"
  - "跌停"
  - "涨停原因"
  - "龙虎榜"
  - "涨停板"
  - "主力资金"
  - "资金流向"
  - "大盘"
  - "板块"
  - "市值"
  - "财报"
  - "年报"
  - "季报"
  - "机构持仓"
  - "北向资金"
  - "融资融券"
  - "股票"
  - "A股"
  - "港股"
  - "美股"
  - "宏观"
  - "CPI"
  - "PMI"
  - "GDP"
capabilities:
  - "finance_api"
  - "chart_generate"
  - "web_search"
output_format: "markdown"
fallback:
  strategy: "degrade"
  message: "无法获取股票数据，正在尝试网页搜索..."
