name: weather_query
description: "天气查询技能 — 通过 QVeris 获取全球城市实时天气、天气预报"
requires:
  bins: []
  env: []
permissions: []
always: false
triggers:
  - "天气"
  - "气温"
  - "下雨"
  - "下雪"
  - "weather"
  - "temperature"
  - "forecast"
  - "明天天气"
  - "今天天气"
  - "穿什么"
  - "带伞"
capabilities:
  - "qveris"
output_format: "markdown"
fallback:
  strategy: "degrade"
  message: "无法获取天气数据。请尝试使用 web_search 搜索天气信息。"
