name: forex_monitor
description: "外汇监控技能 — finance_api免费数据，获取实时汇率、汇率走势、外汇换算，零API Key"
requires:
  bins: []
  env: []
permissions: []
always: false
triggers:
  - "汇率"
  - "外汇"
  - "换汇"
  - "美元"
  - "人民币"
  - "forex"
  - "exchange rate"
  - "currency"
  - "USD"
  - "CNY"
  - "EUR"
  - "JPY"
  - "GBP"
capabilities:
  - "finance_api"
output_format: "markdown"
fallback:
  strategy: "degrade"
  message: "无法获取汇率数据。将尝试使用免费汇率 API。"
