name: chrome_control
description: "浏览器自动化技能 — 控制可见的 Chrome 浏览器窗口，执行打开网页、搜索、点击、输入等操作"
requires:
  bins: []
  env: []
permissions:
  - system.accessibility
  - system.automation
always: false
triggers:
  - "打开浏览器"
  - "打开百度"
  - "打开谷歌"
  - "打开网页"
  - "搜索"
  - "帮我搜"
  - "浏览器"
  - "open chrome"
  - "open browser"
  - "search for"
  - "go to website"
  - "打开网站"
  - "上网"
  - "百度搜索"
  - "谷歌搜索"
  - "google搜索"
capabilities:
  - "chrome_control"
output_format: "markdown"
fallback:
  strategy: "degrade"
  message: "无法控制 Chrome 浏览器。请确保已安装 Google Chrome 并在系统偏好设置 > 安全性与隐私 > 辅助功能中授权终端。"
